apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
  annotations:
    avp.kubernetes.io/path: kv-v2/data/argocd
type: Opaque
stringData:
  api-token: <cert-manager-api-token>
