server:
  ingress:
    enabled: true
    hosts:
      - host: eas.skynetinc.tech
        paths: []
  ha:
    enabled: true
    replicas: 3
    raft:
      enabled: true
      config: |
        ui = true

        service_registration "kubernetes" {}

        listener "tcp" {
          address = "0.0.0.0:8200"
          cluster_address = "0.0.0.0:8201"
          tls_disable = "true"
        }

        storage "raft" {
          path = "/vault/data"
        }
