apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: kv-v2/data/linkerd
spec:
  project: default
  sources:
    - chart: linkerd-control-plane
      repoURL: https://helm.linkerd.io/edge
      targetRevision: 2024.11.8
      helm:
        parameters:
          - name: identityTrustAnchorsPEM
            value: |-
             <trust-anchor>
          - name: identity.issuer.tls.crtPEM
            value: |-
              <issuer-cert>
          - name: identity.issuer.tls.keyPEM
            value: |-
              <issuer-key>
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
