apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: kv-v2/data/linkerd  # Specifies the Vault path for AVP
spec:
  project: default
  sources:
    - chart: linkerd-control-plane
      repoURL: https://helm.linkerd.io/edge
      targetRevision: 2024.11.8
      helm:
        parameters:
          - name: identityTrustAnchorsPEM
            value: "<path:kv-v2/data/linkerd#trust-anchor>"
          - name: identity.issuer.tls.crtPEM
            value: "<path:kv-v2/data/linkerd#issuer-cert>"
          - name: identity.issuer.tls.keyPEM
            value: "<path:kv-v2/data/linkerd#issuer-key>"
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
