apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    namespace: hashicorp
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/WorldDrknss/ArgoCD-Public.git
      path: argocd-vault-ddm-storage
      targetRevision: HEAD
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: 0.29.1
      helm:
        values: |
          server:
            serviceAccount:
              create: false
              name: "vault-sa"

            auditStorage:
              enabled: true

            ha:
              enabled: true
              replicas: 3
              config: |
                ui = true

                listener "tcp" {
                  address = "0.0.0.0:8200"
                  cluster_address = "0.0.0.0:8201"
                  tls_disable = "true"
                }

                # DynamoDB storage backend configuration
                storage "dynamodb" {
                  ha_enabled = "true"
                  table = "<TABLENAME>"  # Replace
                  region = "<REGION>"       # Replace
                }

                # Seal using AWS KMS
                seal "awskms" {
                  region = "<REGION>" # Replace
                  kms_key_id = "<KEYID>" # Replace
                }
