apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd-control-plane
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/WorldDrknss/ArgoCD-Public.git
      path: "argocd-linkerd/control-plane/manifests"
      ref: values
      targetRevision: main
    - chart: linkerd-control-plane
      repoURL: https://helm.linkerd.io/edge
      targetRevision: 2024.11.8
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: linkerd-identity-issuer
      namespace: linkerd
      jsonPointers:
        - /data
    - group: ""
      kind: ConfigMap
      name: linkerd-config
      namespace: linkerd
      jsonPointers:
        - /data
