apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-config
  namespace: linkerd
  annotations:
    avp.kubernetes.io/path: kv-v2/data/linkerd
data:
  trustAnchorsPEM: "<path:kv-v2/data/linkerd#trust-anchor>"
