apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-identity-trust-roots
  namespace: linkerd
  annotations:
    avp.kubernetes.io/path: kv-v2/data/linkerd
data:
  test: "<path:kv-v2/data/linkerd#trust-anchor>"
