apiVersion: v1
kind: Secret
metadata:
  name: linkerd-secrets
  namespace: linkerd
  annotations:
    avp.kubernetes.io/path: kv-v2/data/linkerd  # AVP will replace the placeholders
type: Opaque
data:
  identityTrustAnchorsPEM: <path:kv-v2/data/linkerd#trust-anchor | base64encode>
  identityIssuerCrtPEM: <path:kv-v2/data/linkerd#issuer-cert | base64encode>
  identityIssuerKeyPEM: <path:kv-v2/data/linkerd#issuer-key | base64encode>
