apiVersion: v1
kind: Secret
metadata:
  name: linkerd-identity-issuer
  namespace: linkerd
  annotations:
    avp.kubernetes.io/path: kv-v2/data/linkerd
type: Opaque
data:
  crt.pem: "<path:kv-v2/data/linkerd#issuer-cert | base64encode>"
  key.pem: "<path:kv-v2/data/linkerd#issuer-key | base64encode>"
