apiVersion: v1
kind: Secret
metadata:
  name: linkerd-secrets
  namespace: linkerd
  annotations:
    avp.kubernetes.io/path: kv-v2/data/linkerd  # AVP will replace the placeholders
type: Opaque
data:
  identityTrustAnchorsPEM: <path:kv-v2/data/linkerd#trust-anchor>
  identityIssuerCrtPEM: <path:kv-v2/data/linkerd#issuer-cert>
  identityIssuerKeyPEM: <path:kv-v2/data/linkerd#issuer-key>
